# Generated by Django 3.0.6 on 2020-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='lng',
            field=models.IntegerField(),
        ),
    ]
